/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ImagixApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ImagixFrontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "ImagixTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ImagixUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "ImagixWebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}