AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Imagix - AI Story Generator API

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  CognitoUserPoolId:
    Type: String
    Default: ""
    Description: Cognito User Pool ID for auth
  CognitoClientId:
    Type: String
    Default: ""
    Description: Cognito App Client ID

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:
  ImagixTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: imagix
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ApiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: imagix-api
      Handler: dist/index.handler
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME: !Ref ImagixTable
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImagixTable
      Events:
        ApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY

  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: imagix-api
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod"
  TableName:
    Description: DynamoDB table name
    Value: !Ref ImagixTable
