/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* biome-ignore-all lint: auto-generated */

/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly IMAGIX_USER_POOL_ID: string
  readonly IMAGIX_USER_POOL_CLIENT_ID: string
  readonly IMAGIX_COGNITO_DOMAIN: string
  readonly IMAGIX_API_URL: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}